name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        
        # 0. Checkout the code from the repository
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: ls




        # 1. Install dependencies of our react application
        # 2. Execute automated steps