name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            output1: ${{ steps.build.outputs.output1 }}
            output2: ${{ steps.build.outputs.output2 }}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "$GITHUB_OUTPUT"
            - name: Build
              id: build
              run: |
                echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> "$GITHUB_OUTPUT"
                echo "output2=value2" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
            - name: Step with mistake
              run: |
                echo "mistake=true" > "$GITHUB_OUTPUT" # This will overwrite the content of the output-file since we are using a single >, but since we are using multiple steps, we are also using multiple output-files
                cat "$GITHUB_OUTPUT"
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'success' }} 

        steps:
            - name: Deploy
              run: echo "Deploying"
            - name: Print Outputs
              run: echo ${{ needs.build.outputs.output1 }}