name: 15 - Working with Matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.operating-systems }}-${{ matrix.node }}
        runs-on: ubuntu-atest
        strategy:
            matrix:
                node: ["18.x", "20.x", "21.x"]
                operating-systems: ["ubuntu-latest", "windows-latest"]
        
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node }}
            
            - name: Perform some tests
              run: echo "Running tests on OS ${{ matrix.operating-systems }} and NodeJS ${{ matrix.node }}"